export const UI_STYLE_OPTIONS = [
  ['modern', 'Modern'],
  ['classicWin', 'Classic Windows'],
  ['compact', 'Compact Utility'],
  ['softGray', 'Soft Gray'],
  ['terminal', 'Terminal Green'],
  ['cyberInk', 'Cyber Ink'],
  ['courtroom', 'Courtroom'],
  ['blueprint', 'Blueprint'],
  ['monoPro', 'Mono Pro'],
];

export function getUiChrome(settings, theme) {
  const style = settings?.uiStyle ?? 'modern';
  const dark = settings?.theme === 'dark';

  if (style === 'classicWin') {
    return {
      id: style,
      fontFamily: 'Tahoma, "MS Sans Serif", Arial, sans-serif',
      toolbarBg: dark ? '#2b2b2b' : '#d4d0c8',
      panelBg: dark ? '#202020' : '#d4d0c8',
      cardBg: dark ? '#202020' : '#d4d0c8',
      inputBg: dark ? '#111' : '#fff',
      border: dark ? '#777' : '#808080',
      borderSubtle: dark ? '#555' : '#ffffff',
      radius: 0,
      cardRadius: 0,
      toolbarHeight: 34,
      tabHeight: 28,
      statusHeight: 20,
      buttonPadding: '2px 10px',
      buttonBg: dark ? '#333' : '#d4d0c8',
      buttonColor: theme.text,
      buttonBorder: dark ? '#777' : '#808080',
      buttonShadow: dark
        ? 'inset 1px 1px 0 #555, inset -1px -1px 0 #000'
        : 'inset 1px 1px 0 #fff, inset -1px -1px 0 #808080',
      cardShadow: 'none',
      modalShadow: 'none',
      tabActiveBg: dark ? '#111' : '#ece9d8',
      tabInactiveBg: 'transparent',
      headerWeight: 700,
      uppercaseLabels: false,
    };
  }

  if (style === 'compact') {
    return {
      id: style,
      fontFamily: 'Arial, Helvetica, sans-serif',
      toolbarBg: theme.bg,
      panelBg: theme.bgSecondary,
      cardBg: theme.bgSecondary,
      inputBg: theme.input,
      border: theme.border,
      borderSubtle: theme.borderSubtle,
      radius: 2,
      cardRadius: 3,
      toolbarHeight: 32,
      tabHeight: 27,
      statusHeight: 18,
      buttonPadding: '2px 8px',
      buttonBg: theme.bg,
      buttonColor: theme.textMuted,
      buttonBorder: theme.border,
      buttonShadow: 'none',
      cardShadow: 'none',
      modalShadow: '0 8px 28px rgba(0,0,0,0.22)',
      tabActiveBg: theme.bgSecondary,
      tabInactiveBg: 'transparent',
      headerWeight: 700,
      uppercaseLabels: true,
    };
  }

  if (style === 'softGray') {
    return {
      id: style,
      fontFamily: 'Inter, "Segoe UI", Arial, sans-serif',
      toolbarBg: dark ? '#20242b' : '#f3f4f6',
      panelBg: dark ? '#1d2128' : '#f8fafc',
      cardBg: dark ? '#20242b' : '#ffffff',
      inputBg: theme.input,
      border: dark ? '#3a4049' : '#d1d5db',
      borderSubtle: dark ? '#2f3540' : '#e5e7eb',
      radius: 6,
      cardRadius: 6,
      toolbarHeight: 40,
      tabHeight: 32,
      statusHeight: 20,
      buttonPadding: '4px 11px',
      buttonBg: dark ? '#262b33' : '#ffffff',
      buttonColor: theme.text,
      buttonBorder: dark ? '#3a4049' : '#d1d5db',
      buttonShadow: 'none',
      cardShadow: dark ? 'none' : '0 1px 2px rgba(15,23,42,0.06)',
      modalShadow: '0 18px 50px rgba(0,0,0,0.28)',
      tabActiveBg: theme.bg,
      tabInactiveBg: 'transparent',
      headerWeight: 750,
      uppercaseLabels: true,
    };
  }

  if (style === 'terminal') {
    return {
      id: style,
      fontFamily: 'Consolas, "Courier New", monospace',
      appBg: dark ? '#020403' : '#f5fff6',
      toolbarBg: dark ? '#06140d' : '#e9f8ec',
      panelBg: dark ? '#07110c' : '#f6fff7',
      cardBg: dark ? '#07110c' : '#ffffff',
      inputBg: dark ? '#020806' : '#ffffff',
      border: dark ? '#1f8f4d' : '#8fd5a8',
      borderSubtle: dark ? '#0d3f24' : '#d0ebd9',
      radius: 0,
      cardRadius: 0,
      toolbarHeight: 38,
      tabHeight: 30,
      statusHeight: 20,
      buttonPadding: '3px 10px',
      buttonBg: dark ? '#041d10' : '#ffffff',
      buttonColor: dark ? '#75ff9f' : '#09642d',
      buttonBorder: dark ? '#1f8f4d' : '#73c993',
      buttonShadow: dark ? '0 0 0 1px rgba(117,255,159,0.14), inset 0 0 14px rgba(31,143,77,0.15)' : 'none',
      cardShadow: dark ? '0 0 28px rgba(31,143,77,0.12)' : '0 1px 2px rgba(9,100,45,0.08)',
      modalShadow: dark ? '0 0 50px rgba(31,143,77,0.24)' : '0 18px 50px rgba(9,100,45,0.16)',
      tabActiveBg: dark ? '#082413' : '#ffffff',
      tabInactiveBg: 'transparent',
      tabActiveShadow: dark ? 'inset 0 -2px 0 #75ff9f' : 'inset 0 -2px 0 #09642d',
      headerWeight: 700,
      uppercaseLabels: true,
    };
  }

  if (style === 'cyberInk') {
    return {
      id: style,
      fontFamily: '"Trebuchet MS", "Segoe UI", Arial, sans-serif',
      appBg: dark ? '#070713' : '#fbfbff',
      toolbarBg: dark ? '#101026' : '#f1f0ff',
      panelBg: dark ? '#0d0d20' : '#ffffff',
      cardBg: dark ? '#12122a' : '#ffffff',
      inputBg: dark ? '#09091a' : '#ffffff',
      border: dark ? '#38346d' : '#d7d2ff',
      borderSubtle: dark ? '#24224c' : '#ece9ff',
      radius: 7,
      cardRadius: 7,
      toolbarHeight: 42,
      tabHeight: 34,
      statusHeight: 22,
      buttonPadding: '5px 12px',
      buttonBg: dark ? '#151536' : '#ffffff',
      buttonColor: dark ? '#d9d7ff' : '#33257c',
      buttonBorder: dark ? '#5a4dca' : '#c8c0ff',
      buttonShadow: dark ? '0 0 18px rgba(90,77,202,0.2)' : '0 1px 8px rgba(90,77,202,0.08)',
      cardShadow: dark ? '0 12px 36px rgba(0,0,0,0.3)' : '0 10px 28px rgba(51,37,124,0.08)',
      modalShadow: dark ? '0 24px 70px rgba(0,0,0,0.58)' : '0 24px 70px rgba(51,37,124,0.18)',
      tabActiveBg: dark ? '#18183a' : '#ffffff',
      tabInactiveBg: 'transparent',
      tabActiveShadow: dark ? '0 0 16px rgba(90,77,202,0.28)' : '0 4px 14px rgba(90,77,202,0.08)',
      headerWeight: 800,
      uppercaseLabels: true,
    };
  }

  if (style === 'courtroom') {
    return {
      id: style,
      fontFamily: 'Georgia, "Times New Roman", serif',
      appBg: dark ? '#13100c' : '#fbfaf6',
      toolbarBg: dark ? '#211a13' : '#eee8dc',
      panelBg: dark ? '#1b160f' : '#f7f1e6',
      cardBg: dark ? '#201912' : '#fffdf8',
      inputBg: dark ? '#120f0b' : '#fffaf0',
      border: dark ? '#5d4a30' : '#cbbd9c',
      borderSubtle: dark ? '#35291b' : '#e6dac0',
      radius: 2,
      cardRadius: 4,
      toolbarHeight: 43,
      tabHeight: 34,
      statusHeight: 22,
      buttonPadding: '5px 12px',
      buttonBg: dark ? '#2b2117' : '#fffaf0',
      buttonColor: dark ? '#f0dfbf' : '#4a321c',
      buttonBorder: dark ? '#6d5738' : '#bca77b',
      buttonShadow: dark ? 'inset 0 1px 0 rgba(255,255,255,0.08)' : 'inset 0 1px 0 #fff, 0 1px 2px rgba(74,50,28,0.08)',
      cardShadow: dark ? 'none' : '0 2px 8px rgba(74,50,28,0.08)',
      modalShadow: '0 24px 70px rgba(25,18,10,0.32)',
      tabActiveBg: dark ? '#15110c' : '#fffdf8',
      tabInactiveBg: 'transparent',
      tabActiveShadow: 'inset 0 -2px 0 currentColor',
      headerWeight: 700,
      uppercaseLabels: false,
    };
  }

  if (style === 'blueprint') {
    return {
      id: style,
      fontFamily: '"Helvetica Neue", Arial, sans-serif',
      appBg: dark ? '#061525' : '#f3f8fc',
      toolbarBg: dark ? '#08223a' : '#e7f1f8',
      panelBg: dark ? '#071b2e' : '#f8fbfd',
      cardBg: dark ? '#09233c' : '#ffffff',
      inputBg: dark ? '#04111e' : '#ffffff',
      border: dark ? '#1d5d89' : '#b8d6e8',
      borderSubtle: dark ? '#103a5a' : '#dcecf5',
      radius: 1,
      cardRadius: 2,
      toolbarHeight: 39,
      tabHeight: 31,
      statusHeight: 20,
      buttonPadding: '4px 10px',
      buttonBg: dark ? '#0a2c4a' : '#ffffff',
      buttonColor: dark ? '#bde8ff' : '#155c86',
      buttonBorder: dark ? '#1d5d89' : '#a8cfe4',
      buttonShadow: 'none',
      cardShadow: 'none',
      modalShadow: dark ? '0 22px 60px rgba(0,0,0,0.42)' : '0 18px 46px rgba(21,92,134,0.12)',
      tabActiveBg: dark ? '#04111e' : '#ffffff',
      tabInactiveBg: 'transparent',
      tabActiveShadow: 'inset 0 -2px 0 currentColor',
      headerWeight: 800,
      uppercaseLabels: true,
    };
  }

  if (style === 'monoPro') {
    return {
      id: style,
      fontFamily: '"Segoe UI", Arial, sans-serif',
      appBg: dark ? '#0e0e10' : '#f9f9f8',
      toolbarBg: dark ? '#17171a' : '#efefed',
      panelBg: dark ? '#151518' : '#ffffff',
      cardBg: dark ? '#1a1a1d' : '#ffffff',
      inputBg: dark ? '#0f0f12' : '#ffffff',
      border: dark ? '#333337' : '#d6d6d2',
      borderSubtle: dark ? '#242428' : '#e9e9e5',
      radius: 3,
      cardRadius: 3,
      toolbarHeight: 37,
      tabHeight: 30,
      statusHeight: 19,
      buttonPadding: '4px 10px',
      buttonBg: dark ? '#202024' : '#ffffff',
      buttonColor: dark ? '#eeeeee' : '#222222',
      buttonBorder: dark ? '#3a3a40' : '#cfcfca',
      buttonShadow: dark ? 'inset 0 1px 0 rgba(255,255,255,0.05)' : '0 1px 0 rgba(0,0,0,0.04)',
      cardShadow: 'none',
      modalShadow: '0 20px 60px rgba(0,0,0,0.25)',
      tabActiveBg: dark ? '#0f0f12' : '#ffffff',
      tabInactiveBg: 'transparent',
      tabActiveShadow: 'inset 0 -2px 0 currentColor',
      headerWeight: 650,
      uppercaseLabels: false,
    };
  }

  return {
    id: 'modern',
    fontFamily: 'Inter, system-ui, sans-serif',
    toolbarBg: theme.bgSecondary,
    panelBg: theme.bgSecondary,
    cardBg: theme.bgSecondary,
    inputBg: theme.input,
    border: theme.border,
    borderSubtle: theme.borderSubtle,
    radius: 4,
    cardRadius: 8,
    toolbarHeight: 40,
    tabHeight: 32,
    statusHeight: 20,
    buttonPadding: '3px 10px',
    buttonBg: 'transparent',
    buttonColor: theme.textMuted,
    buttonBorder: theme.border,
    buttonShadow: 'none',
    cardShadow: 'none',
    modalShadow: '0 20px 60px rgba(0,0,0,0.5)',
    tabActiveBg: theme.bg,
    tabInactiveBg: 'transparent',
    headerWeight: 800,
    uppercaseLabels: true,
  };
}

export function chromeButton(theme, ui, extra = {}) {
  return {
    padding: ui.buttonPadding,
    background: ui.buttonBg,
    border: `1px solid ${ui.buttonBorder}`,
    borderRadius: ui.radius,
    boxShadow: ui.buttonShadow,
    color: ui.buttonColor,
    fontSize: 12,
    cursor: 'pointer',
    fontFamily: 'inherit',
    ...extra,
  };
}
